version: '3.8'

services:
  backend:
    build: ./backend
    command: ["/app/entrypoint.sh"]
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventuser -d eventdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./backend/staticfiles:/static
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge